spring.application.name=notebookmgt 
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/notebookmgt_db
spring.datasource.username=postgres
spring.datasource.password=herman
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect